- hosts: BFT
  remote_user: root
  tasks:
    - name: clone BFT
      copy:
        src: /vagrant/BFT/BFT
        dest: /root/BFT{{item}}/
      loop:
        - 0
      when: (ansible_hostname is not match "node0")

    - name: clone BFT
      copy:
        src: /vagrant/BFT/BFT
        dest: /root/BFT{{item}}/
      loop:
        - 0
      when: (ansible_hostname is match "node0")

    - name: chmod BFT
      shell: chmod +x /root/BFT{{item}}/BFT
      loop:
        - 0
      when: (ansible_hostname is not match "node0")

    - name: chmod BFT
      shell: chmod +x /root/BFT{{item}}/BFT
      loop:
        - 0
      when: (ansible_hostname is match "node0")
