- hosts: BFT
  remote_user: root
  tasks:
    - name: create testbed dirs
      file:
        path: /root/testbed
        state: directory

    - name: run BFT as a daemon
      shell: "(nohup ./BFT > /root/testbed/{{inventory_hostname}}_{{item}}.txt 2>&1 &)"
      args:
        chdir: /root/BFT{{item}}
      loop:
        - 0
      when: (ansible_hostname is match "node0")

    - name: run BFT as a daemon
      shell: "(nohup ./BFT > /root/testbed/{{inventory_hostname}}_{{item}}.txt 2>&1 &)"
      args:
        chdir: /root/BFT{{item}}
      loop:
        - 0
      when: (ansible_hostname is not match "node0")

    # - name: test net_flow
    #   shell: "(nohup iftop -t -P -N -n -s 150 > /root/net_flow.txt 2>&1 &)"
    #   args:
    #     chdir: /root/
    #   when: (ansible_hostname is match "node0")
